// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: Ticket.proto

package ticket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AGENT int32

const (
	AGENT_BROWSER AGENT = 0
	AGENT_MOBILE  AGENT = 1
)

// Enum value maps for AGENT.
var (
	AGENT_name = map[int32]string{
		0: "BROWSER",
		1: "MOBILE",
	}
	AGENT_value = map[string]int32{
		"BROWSER": 0,
		"MOBILE":  1,
	}
)

func (x AGENT) Enum() *AGENT {
	p := new(AGENT)
	*p = x
	return p
}

func (x AGENT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AGENT) Descriptor() protoreflect.EnumDescriptor {
	return file_Ticket_proto_enumTypes[0].Descriptor()
}

func (AGENT) Type() protoreflect.EnumType {
	return &file_Ticket_proto_enumTypes[0]
}

func (x AGENT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AGENT.Descriptor instead.
func (AGENT) EnumDescriptor() ([]byte, []int) {
	return file_Ticket_proto_rawDescGZIP(), []int{0}
}

type Hash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Hash) Reset() {
	*x = Hash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Ticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_Ticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash.ProtoReflect.Descriptor instead.
func (*Hash) Descriptor() ([]byte, []int) {
	return file_Ticket_proto_rawDescGZIP(), []int{0}
}

func (x *Hash) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Cookie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Cookie) Reset() {
	*x = Cookie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Ticket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookie) ProtoMessage() {}

func (x *Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_Ticket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookie.ProtoReflect.Descriptor instead.
func (*Cookie) Descriptor() ([]byte, []int) {
	return file_Ticket_proto_rawDescGZIP(), []int{1}
}

func (x *Cookie) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Proxy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP       string  `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port     string  `protobuf:"bytes,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Username *string `protobuf:"bytes,3,opt,name=Username,proto3,oneof" json:"Username,omitempty"`
	Password *string `protobuf:"bytes,4,opt,name=Password,proto3,oneof" json:"Password,omitempty"`
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Ticket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_Ticket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_Ticket_proto_rawDescGZIP(), []int{2}
}

func (x *Proxy) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *Proxy) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Proxy) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *Proxy) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type DeobfsucateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proxy *Proxy `protobuf:"bytes,1,opt,name=Proxy,proto3" json:"Proxy,omitempty"`
	Agent AGENT  `protobuf:"varint,2,opt,name=Agent,proto3,enum=ticket.AGENT" json:"Agent,omitempty"`
}

func (x *DeobfsucateRequest) Reset() {
	*x = DeobfsucateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Ticket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeobfsucateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeobfsucateRequest) ProtoMessage() {}

func (x *DeobfsucateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Ticket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeobfsucateRequest.ProtoReflect.Descriptor instead.
func (*DeobfsucateRequest) Descriptor() ([]byte, []int) {
	return file_Ticket_proto_rawDescGZIP(), []int{3}
}

func (x *DeobfsucateRequest) GetProxy() *Proxy {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *DeobfsucateRequest) GetAgent() AGENT {
	if x != nil {
		return x.Agent
	}
	return AGENT_BROWSER
}

type GenerateCookieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proxy *Proxy `protobuf:"bytes,1,opt,name=Proxy,proto3" json:"Proxy,omitempty"`
	Hash  string `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *GenerateCookieRequest) Reset() {
	*x = GenerateCookieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Ticket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCookieRequest) ProtoMessage() {}

func (x *GenerateCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Ticket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCookieRequest.ProtoReflect.Descriptor instead.
func (*GenerateCookieRequest) Descriptor() ([]byte, []int) {
	return file_Ticket_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateCookieRequest) GetProxy() *Proxy {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *GenerateCookieRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_Ticket_proto protoreflect.FileDescriptor

var file_Ticket_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x1c, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x1f, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5e,
	0x0a, 0x12, 0x44, 0x65, 0x6f, 0x62, 0x66, 0x73, 0x75, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x52, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x52, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x50,
	0x0a, 0x15, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68,
	0x2a, 0x20, 0x0a, 0x05, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x52, 0x4f,
	0x57, 0x53, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45,
	0x10, 0x01, 0x32, 0x82, 0x01, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x37, 0x0a,
	0x0b, 0x44, 0x65, 0x6f, 0x62, 0x66, 0x75, 0x73, 0x63, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x44, 0x65, 0x6f, 0x62, 0x66, 0x73, 0x75, 0x63, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x3f, 0x0a, 0x0e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x1d, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Ticket_proto_rawDescOnce sync.Once
	file_Ticket_proto_rawDescData = file_Ticket_proto_rawDesc
)

func file_Ticket_proto_rawDescGZIP() []byte {
	file_Ticket_proto_rawDescOnce.Do(func() {
		file_Ticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_Ticket_proto_rawDescData)
	})
	return file_Ticket_proto_rawDescData
}

var file_Ticket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Ticket_proto_goTypes = []interface{}{
	(AGENT)(0),                    // 0: ticket.AGENT
	(*Hash)(nil),                  // 1: ticket.Hash
	(*Cookie)(nil),                // 2: ticket.Cookie
	(*Proxy)(nil),                 // 3: ticket.Proxy
	(*DeobfsucateRequest)(nil),    // 4: ticket.DeobfsucateRequest
	(*GenerateCookieRequest)(nil), // 5: ticket.GenerateCookieRequest
}
var file_Ticket_proto_depIdxs = []int32{
	3, // 0: ticket.DeobfsucateRequest.Proxy:type_name -> ticket.Proxy
	0, // 1: ticket.DeobfsucateRequest.Agent:type_name -> ticket.AGENT
	3, // 2: ticket.GenerateCookieRequest.Proxy:type_name -> ticket.Proxy
	4, // 3: ticket.Ticket.Deobfuscate:input_type -> ticket.DeobfsucateRequest
	5, // 4: ticket.Ticket.GenerateCookie:input_type -> ticket.GenerateCookieRequest
	1, // 5: ticket.Ticket.Deobfuscate:output_type -> ticket.Hash
	2, // 6: ticket.Ticket.GenerateCookie:output_type -> ticket.Cookie
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Ticket_proto_init() }
func file_Ticket_proto_init() {
	if File_Ticket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Ticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Ticket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cookie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Ticket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proxy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Ticket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeobfsucateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Ticket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCookieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Ticket_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Ticket_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Ticket_proto_goTypes,
		DependencyIndexes: file_Ticket_proto_depIdxs,
		EnumInfos:         file_Ticket_proto_enumTypes,
		MessageInfos:      file_Ticket_proto_msgTypes,
	}.Build()
	File_Ticket_proto = out.File
	file_Ticket_proto_rawDesc = nil
	file_Ticket_proto_goTypes = nil
	file_Ticket_proto_depIdxs = nil
}
