// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ticket

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TicketClient is the client API for Ticket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketClient interface {
	Deobfuscate(ctx context.Context, in *DeobfsucateRequest, opts ...grpc.CallOption) (*Hash, error)
	GenerateCookie(ctx context.Context, in *GenerateCookieRequest, opts ...grpc.CallOption) (*Cookie, error)
}

type ticketClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketClient(cc grpc.ClientConnInterface) TicketClient {
	return &ticketClient{cc}
}

func (c *ticketClient) Deobfuscate(ctx context.Context, in *DeobfsucateRequest, opts ...grpc.CallOption) (*Hash, error) {
	out := new(Hash)
	err := c.cc.Invoke(ctx, "/ticket.Ticket/Deobfuscate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) GenerateCookie(ctx context.Context, in *GenerateCookieRequest, opts ...grpc.CallOption) (*Cookie, error) {
	out := new(Cookie)
	err := c.cc.Invoke(ctx, "/ticket.Ticket/GenerateCookie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServer is the server API for Ticket service.
// All implementations must embed UnimplementedTicketServer
// for forward compatibility
type TicketServer interface {
	Deobfuscate(context.Context, *DeobfsucateRequest) (*Hash, error)
	GenerateCookie(context.Context, *GenerateCookieRequest) (*Cookie, error)
	mustEmbedUnimplementedTicketServer()
}

// UnimplementedTicketServer must be embedded to have forward compatible implementations.
type UnimplementedTicketServer struct {
}

func (UnimplementedTicketServer) Deobfuscate(context.Context, *DeobfsucateRequest) (*Hash, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deobfuscate not implemented")
}
func (UnimplementedTicketServer) GenerateCookie(context.Context, *GenerateCookieRequest) (*Cookie, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCookie not implemented")
}
func (UnimplementedTicketServer) mustEmbedUnimplementedTicketServer() {}

// UnsafeTicketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServer will
// result in compilation errors.
type UnsafeTicketServer interface {
	mustEmbedUnimplementedTicketServer()
}

func RegisterTicketServer(s grpc.ServiceRegistrar, srv TicketServer) {
	s.RegisterService(&Ticket_ServiceDesc, srv)
}

func _Ticket_Deobfuscate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeobfsucateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).Deobfuscate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/Deobfuscate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).Deobfuscate(ctx, req.(*DeobfsucateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_GenerateCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).GenerateCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.Ticket/GenerateCookie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).GenerateCookie(ctx, req.(*GenerateCookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ticket_ServiceDesc is the grpc.ServiceDesc for Ticket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ticket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.Ticket",
	HandlerType: (*TicketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deobfuscate",
			Handler:    _Ticket_Deobfuscate_Handler,
		},
		{
			MethodName: "GenerateCookie",
			Handler:    _Ticket_GenerateCookie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Ticket.proto",
}
